/* 
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mynhs.sdk.Client.SwaggerDateConverter;

namespace mynhs.sdk.Model
{
    /// <summary>
    /// Diastolic/Systolic
    /// </summary>
    [DataContract]
        public partial class BloodPressure :  IEquatable<BloodPressure>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BloodPressure" /> class.
        /// </summary>
        /// <param name="systolic">The bigger number (the first number).</param>
        /// <param name="diastolic">The smaller number (the second number).</param>
        public BloodPressure(long? systolic = default(long?), long? diastolic = default(long?))
        {
            this.Systolic = systolic;
            this.Diastolic = diastolic;
        }
        
        /// <summary>
        /// The bigger number (the first number)
        /// </summary>
        /// <value>The bigger number (the first number)</value>
        [DataMember(Name="Systolic", EmitDefaultValue=false)]
        public long? Systolic { get; set; }

        /// <summary>
        /// The smaller number (the second number)
        /// </summary>
        /// <value>The smaller number (the second number)</value>
        [DataMember(Name="Diastolic", EmitDefaultValue=false)]
        public long? Diastolic { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BloodPressure {\n");
            sb.Append("  Systolic: ").Append(Systolic).Append("\n");
            sb.Append("  Diastolic: ").Append(Diastolic).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BloodPressure);
        }

        /// <summary>
        /// Returns true if BloodPressure instances are equal
        /// </summary>
        /// <param name="input">Instance of BloodPressure to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BloodPressure input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Systolic == input.Systolic ||
                    (this.Systolic != null &&
                    this.Systolic.Equals(input.Systolic))
                ) && 
                (
                    this.Diastolic == input.Diastolic ||
                    (this.Diastolic != null &&
                    this.Diastolic.Equals(input.Diastolic))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Systolic != null)
                    hashCode = hashCode * 59 + this.Systolic.GetHashCode();
                if (this.Diastolic != null)
                    hashCode = hashCode * 59 + this.Diastolic.GetHashCode();
                return hashCode;
            }
        }
    }
}
