/* 
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mynhs.sdk.Client.SwaggerDateConverter;

namespace mynhs.sdk.Model
{
    /// <summary>
    /// Colesterol
    /// </summary>
    [DataContract]
        public partial class Colesterol :  IEquatable<Colesterol>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Colesterol" /> class.
        /// </summary>
        /// <param name="lDL">mg/dL.</param>
        /// <param name="hDL">mg/dL.</param>
        /// <param name="totalCholesterol">mg/dL.</param>
        /// <param name="triglycerides">mg/dL.</param>
        /// <param name="vldlLevels">mg/dL.</param>
        public Colesterol(decimal? lDL = default(decimal?), decimal? hDL = default(decimal?), decimal? totalCholesterol = default(decimal?), decimal? triglycerides = default(decimal?), decimal? vldlLevels = default(decimal?))
        {
            this.LDL = lDL;
            this.HDL = hDL;
            this.TotalCholesterol = totalCholesterol;
            this.Triglycerides = triglycerides;
            this.VldlLevels = vldlLevels;
        }
        
        /// <summary>
        /// mg/dL
        /// </summary>
        /// <value>mg/dL</value>
        [DataMember(Name="LDL", EmitDefaultValue=false)]
        public decimal? LDL { get; set; }

        /// <summary>
        /// mg/dL
        /// </summary>
        /// <value>mg/dL</value>
        [DataMember(Name="HDL", EmitDefaultValue=false)]
        public decimal? HDL { get; set; }

        /// <summary>
        /// mg/dL
        /// </summary>
        /// <value>mg/dL</value>
        [DataMember(Name="TotalCholesterol", EmitDefaultValue=false)]
        public decimal? TotalCholesterol { get; set; }

        /// <summary>
        /// mg/dL
        /// </summary>
        /// <value>mg/dL</value>
        [DataMember(Name="Triglycerides", EmitDefaultValue=false)]
        public decimal? Triglycerides { get; set; }

        /// <summary>
        /// mg/dL
        /// </summary>
        /// <value>mg/dL</value>
        [DataMember(Name="VldlLevels", EmitDefaultValue=false)]
        public decimal? VldlLevels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Colesterol {\n");
            sb.Append("  LDL: ").Append(LDL).Append("\n");
            sb.Append("  HDL: ").Append(HDL).Append("\n");
            sb.Append("  TotalCholesterol: ").Append(TotalCholesterol).Append("\n");
            sb.Append("  Triglycerides: ").Append(Triglycerides).Append("\n");
            sb.Append("  VldlLevels: ").Append(VldlLevels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Colesterol);
        }

        /// <summary>
        /// Returns true if Colesterol instances are equal
        /// </summary>
        /// <param name="input">Instance of Colesterol to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Colesterol input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LDL == input.LDL ||
                    (this.LDL != null &&
                    this.LDL.Equals(input.LDL))
                ) && 
                (
                    this.HDL == input.HDL ||
                    (this.HDL != null &&
                    this.HDL.Equals(input.HDL))
                ) && 
                (
                    this.TotalCholesterol == input.TotalCholesterol ||
                    (this.TotalCholesterol != null &&
                    this.TotalCholesterol.Equals(input.TotalCholesterol))
                ) && 
                (
                    this.Triglycerides == input.Triglycerides ||
                    (this.Triglycerides != null &&
                    this.Triglycerides.Equals(input.Triglycerides))
                ) && 
                (
                    this.VldlLevels == input.VldlLevels ||
                    (this.VldlLevels != null &&
                    this.VldlLevels.Equals(input.VldlLevels))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LDL != null)
                    hashCode = hashCode * 59 + this.LDL.GetHashCode();
                if (this.HDL != null)
                    hashCode = hashCode * 59 + this.HDL.GetHashCode();
                if (this.TotalCholesterol != null)
                    hashCode = hashCode * 59 + this.TotalCholesterol.GetHashCode();
                if (this.Triglycerides != null)
                    hashCode = hashCode * 59 + this.Triglycerides.GetHashCode();
                if (this.VldlLevels != null)
                    hashCode = hashCode * 59 + this.VldlLevels.GetHashCode();
                return hashCode;
            }
        }
    }
}
