/* 
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mynhs.sdk.Client.SwaggerDateConverter;

namespace mynhs.sdk.Model
{
    /// <summary>
    /// SubmissionResponseDetails
    /// </summary>
    [DataContract]
        public partial class SubmissionResponseDetails :  IEquatable<SubmissionResponseDetails>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmissionResponseDetails" /> class.
        /// </summary>
        /// <param name="systemName">systemName.</param>
        /// <param name="status">status.</param>
        /// <param name="isCompletedSuccessfully">isCompletedSuccessfully.</param>
        /// <param name="percentComplete">percentComplete.</param>
        /// <param name="dateStarted">dateStarted.</param>
        /// <param name="dateFinished">dateFinished.</param>
        /// <param name="dateUpdated">dateUpdated.</param>
        public SubmissionResponseDetails(string systemName = default(string), StatusEnum status = default(StatusEnum), bool? isCompletedSuccessfully = default(bool?), int? percentComplete = default(int?), DateTimeOffset? dateStarted = default(DateTimeOffset?), DateTimeOffset? dateFinished = default(DateTimeOffset?), DateTimeOffset? dateUpdated = default(DateTimeOffset?))
        {
            this.SystemName = systemName;
            this.Status = status;
            this.IsCompletedSuccessfully = isCompletedSuccessfully;
            this.PercentComplete = percentComplete;
            this.DateStarted = dateStarted;
            this.DateFinished = dateFinished;
            this.DateUpdated = dateUpdated;
        }
        
        /// <summary>
        /// Gets or Sets SystemName
        /// </summary>
        [DataMember(Name="SystemName", EmitDefaultValue=false)]
        public string SystemName { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="Status", EmitDefaultValue=false)]
        public StatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets IsCompletedSuccessfully
        /// </summary>
        [DataMember(Name="IsCompletedSuccessfully", EmitDefaultValue=false)]
        public bool? IsCompletedSuccessfully { get; set; }

        /// <summary>
        /// Gets or Sets PercentComplete
        /// </summary>
        [DataMember(Name="PercentComplete", EmitDefaultValue=false)]
        public int? PercentComplete { get; set; }

        /// <summary>
        /// Gets or Sets DateStarted
        /// </summary>
        [DataMember(Name="DateStarted", EmitDefaultValue=false)]
        public DateTimeOffset? DateStarted { get; set; }

        /// <summary>
        /// Gets or Sets DateFinished
        /// </summary>
        [DataMember(Name="DateFinished", EmitDefaultValue=false)]
        public DateTimeOffset? DateFinished { get; set; }

        /// <summary>
        /// Gets or Sets DateUpdated
        /// </summary>
        [DataMember(Name="DateUpdated", EmitDefaultValue=false)]
        public DateTimeOffset? DateUpdated { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SubmissionResponseDetails {\n");
            sb.Append("  SystemName: ").Append(SystemName).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  IsCompletedSuccessfully: ").Append(IsCompletedSuccessfully).Append("\n");
            sb.Append("  PercentComplete: ").Append(PercentComplete).Append("\n");
            sb.Append("  DateStarted: ").Append(DateStarted).Append("\n");
            sb.Append("  DateFinished: ").Append(DateFinished).Append("\n");
            sb.Append("  DateUpdated: ").Append(DateUpdated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubmissionResponseDetails);
        }

        /// <summary>
        /// Returns true if SubmissionResponseDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of SubmissionResponseDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmissionResponseDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SystemName == input.SystemName ||
                    (this.SystemName != null &&
                    this.SystemName.Equals(input.SystemName))
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.IsCompletedSuccessfully == input.IsCompletedSuccessfully ||
                    (this.IsCompletedSuccessfully != null &&
                    this.IsCompletedSuccessfully.Equals(input.IsCompletedSuccessfully))
                ) && 
                (
                    this.PercentComplete == input.PercentComplete ||
                    (this.PercentComplete != null &&
                    this.PercentComplete.Equals(input.PercentComplete))
                ) && 
                (
                    this.DateStarted == input.DateStarted ||
                    (this.DateStarted != null &&
                    this.DateStarted.Equals(input.DateStarted))
                ) && 
                (
                    this.DateFinished == input.DateFinished ||
                    (this.DateFinished != null &&
                    this.DateFinished.Equals(input.DateFinished))
                ) && 
                (
                    this.DateUpdated == input.DateUpdated ||
                    (this.DateUpdated != null &&
                    this.DateUpdated.Equals(input.DateUpdated))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SystemName != null)
                    hashCode = hashCode * 59 + this.SystemName.GetHashCode();
                if (this.Status != null)
                    hashCode = hashCode * 59 + this.Status.GetHashCode();
                if (this.IsCompletedSuccessfully != null)
                    hashCode = hashCode * 59 + this.IsCompletedSuccessfully.GetHashCode();
                if (this.PercentComplete != null)
                    hashCode = hashCode * 59 + this.PercentComplete.GetHashCode();
                if (this.DateStarted != null)
                    hashCode = hashCode * 59 + this.DateStarted.GetHashCode();
                if (this.DateFinished != null)
                    hashCode = hashCode * 59 + this.DateFinished.GetHashCode();
                if (this.DateUpdated != null)
                    hashCode = hashCode * 59 + this.DateUpdated.GetHashCode();
                return hashCode;
            }
        }
    }
}
