/* 
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using mynhs.sdk.Client;
using mynhs.sdk.Model;

namespace mynhs.sdk.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IObservationsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>NhsProfile</returns>
        NhsProfile MynhsUserIdObservationsObservationTypeGet (string userId, string observationType, int? skip = null, int? limit = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>ApiResponse of NhsProfile</returns>
        ApiResponse<NhsProfile> MynhsUserIdObservationsObservationTypeGetWithHttpInfo (string userId, string observationType, int? skip = null, int? limit = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>NhsProfile</returns>
        NhsProfile MynhsUserIdObservationsSummariesGet (string userId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>ApiResponse of NhsProfile</returns>
        ApiResponse<NhsProfile> MynhsUserIdObservationsSummariesGetWithHttpInfo (string userId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>NhsProfile</returns>
        NhsProfile MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet (string userId, string observationType, string queryType, decimal? pastDays);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>ApiResponse of NhsProfile</returns>
        ApiResponse<NhsProfile> MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetWithHttpInfo (string userId, string observationType, string queryType, decimal? pastDays);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>Task of NhsProfile</returns>
        System.Threading.Tasks.Task<NhsProfile> MynhsUserIdObservationsObservationTypeGetAsync (string userId, string observationType, int? skip = null, int? limit = null);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>Task of ApiResponse (NhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<NhsProfile>> MynhsUserIdObservationsObservationTypeGetAsyncWithHttpInfo (string userId, string observationType, int? skip = null, int? limit = null);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>Task of NhsProfile</returns>
        System.Threading.Tasks.Task<NhsProfile> MynhsUserIdObservationsSummariesGetAsync (string userId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>Task of ApiResponse (NhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<NhsProfile>> MynhsUserIdObservationsSummariesGetAsyncWithHttpInfo (string userId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>Task of NhsProfile</returns>
        System.Threading.Tasks.Task<NhsProfile> MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetAsync (string userId, string observationType, string queryType, decimal? pastDays);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>Task of ApiResponse (NhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<NhsProfile>> MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetAsyncWithHttpInfo (string userId, string observationType, string queryType, decimal? pastDays);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class ObservationsApi : IObservationsApi
    {
        private mynhs.sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservationsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ObservationsApi(String basePath)
        {
            this.Configuration = new mynhs.sdk.Client.Configuration { BasePath = basePath };

            ExceptionFactory = mynhs.sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservationsApi"/> class
        /// </summary>
        /// <returns></returns>
        public ObservationsApi()
        {
            this.Configuration = mynhs.sdk.Client.Configuration.Default;

            ExceptionFactory = mynhs.sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ObservationsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ObservationsApi(mynhs.sdk.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = mynhs.sdk.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = mynhs.sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public mynhs.sdk.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public mynhs.sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>NhsProfile</returns>
        public NhsProfile MynhsUserIdObservationsObservationTypeGet (string userId, string observationType, int? skip = null, int? limit = null)
        {
             ApiResponse<NhsProfile> localVarResponse = MynhsUserIdObservationsObservationTypeGetWithHttpInfo(userId, observationType, skip, limit);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>ApiResponse of NhsProfile</returns>
        public ApiResponse< NhsProfile > MynhsUserIdObservationsObservationTypeGetWithHttpInfo (string userId, string observationType, int? skip = null, int? limit = null)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ObservationsApi->MynhsUserIdObservationsObservationTypeGet");
            // verify the required parameter 'observationType' is set
            if (observationType == null)
                throw new ApiException(400, "Missing required parameter 'observationType' when calling ObservationsApi->MynhsUserIdObservationsObservationTypeGet");

            var localVarPath = "./mynhs/{userId}/observations/{observationType}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (observationType != null) localVarPathParams.Add("observationType", this.Configuration.ApiClient.ParameterToString(observationType)); // path parameter
            if (skip != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "skip", skip)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsUserIdObservationsObservationTypeGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (NhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>Task of NhsProfile</returns>
        public async System.Threading.Tasks.Task<NhsProfile> MynhsUserIdObservationsObservationTypeGetAsync (string userId, string observationType, int? skip = null, int? limit = null)
        {
             ApiResponse<NhsProfile> localVarResponse = await MynhsUserIdObservationsObservationTypeGetAsyncWithHttpInfo(userId, observationType, skip, limit);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="skip">The number of items to skip before starting to collect the result set. (optional)</param>
        /// <param name="limit">The numbers of items to return. (optional, default to 20)</param>
        /// <returns>Task of ApiResponse (NhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NhsProfile>> MynhsUserIdObservationsObservationTypeGetAsyncWithHttpInfo (string userId, string observationType, int? skip = null, int? limit = null)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ObservationsApi->MynhsUserIdObservationsObservationTypeGet");
            // verify the required parameter 'observationType' is set
            if (observationType == null)
                throw new ApiException(400, "Missing required parameter 'observationType' when calling ObservationsApi->MynhsUserIdObservationsObservationTypeGet");

            var localVarPath = "./mynhs/{userId}/observations/{observationType}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (observationType != null) localVarPathParams.Add("observationType", this.Configuration.ApiClient.ParameterToString(observationType)); // path parameter
            if (skip != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "skip", skip)); // query parameter
            if (limit != null) localVarQueryParams.AddRange(this.Configuration.ApiClient.ParameterToKeyValuePairs("", "limit", limit)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsUserIdObservationsObservationTypeGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (NhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>NhsProfile</returns>
        public NhsProfile MynhsUserIdObservationsSummariesGet (string userId)
        {
             ApiResponse<NhsProfile> localVarResponse = MynhsUserIdObservationsSummariesGetWithHttpInfo(userId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>ApiResponse of NhsProfile</returns>
        public ApiResponse< NhsProfile > MynhsUserIdObservationsSummariesGetWithHttpInfo (string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ObservationsApi->MynhsUserIdObservationsSummariesGet");

            var localVarPath = "./mynhs/{userId}/observations/summaries";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsUserIdObservationsSummariesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (NhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>Task of NhsProfile</returns>
        public async System.Threading.Tasks.Task<NhsProfile> MynhsUserIdObservationsSummariesGetAsync (string userId)
        {
             ApiResponse<NhsProfile> localVarResponse = await MynhsUserIdObservationsSummariesGetAsyncWithHttpInfo(userId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <returns>Task of ApiResponse (NhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NhsProfile>> MynhsUserIdObservationsSummariesGetAsyncWithHttpInfo (string userId)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ObservationsApi->MynhsUserIdObservationsSummariesGet");

            var localVarPath = "./mynhs/{userId}/observations/summaries";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsUserIdObservationsSummariesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (NhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>NhsProfile</returns>
        public NhsProfile MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet (string userId, string observationType, string queryType, decimal? pastDays)
        {
             ApiResponse<NhsProfile> localVarResponse = MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetWithHttpInfo(userId, observationType, queryType, pastDays);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>ApiResponse of NhsProfile</returns>
        public ApiResponse< NhsProfile > MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetWithHttpInfo (string userId, string observationType, string queryType, decimal? pastDays)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");
            // verify the required parameter 'observationType' is set
            if (observationType == null)
                throw new ApiException(400, "Missing required parameter 'observationType' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");
            // verify the required parameter 'queryType' is set
            if (queryType == null)
                throw new ApiException(400, "Missing required parameter 'queryType' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");
            // verify the required parameter 'pastDays' is set
            if (pastDays == null)
                throw new ApiException(400, "Missing required parameter 'pastDays' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");

            var localVarPath = "./mynhs/{userId}/observations/summaries/{observationType}/{queryType}/{pastDays}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (observationType != null) localVarPathParams.Add("observationType", this.Configuration.ApiClient.ParameterToString(observationType)); // path parameter
            if (queryType != null) localVarPathParams.Add("queryType", this.Configuration.ApiClient.ParameterToString(queryType)); // path parameter
            if (pastDays != null) localVarPathParams.Add("pastDays", this.Configuration.ApiClient.ParameterToString(pastDays)); // path parameter
            // authentication (MyNhsOAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (NhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>Task of NhsProfile</returns>
        public async System.Threading.Tasks.Task<NhsProfile> MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetAsync (string userId, string observationType, string queryType, decimal? pastDays)
        {
             ApiResponse<NhsProfile> localVarResponse = await MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetAsyncWithHttpInfo(userId, observationType, queryType, pastDays);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="mynhs.sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId">The User Id to access</param>
        /// <param name="observationType"></param>
        /// <param name="queryType"></param>
        /// <param name="pastDays"></param>
        /// <returns>Task of ApiResponse (NhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<NhsProfile>> MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGetAsyncWithHttpInfo (string userId, string observationType, string queryType, decimal? pastDays)
        {
            // verify the required parameter 'userId' is set
            if (userId == null)
                throw new ApiException(400, "Missing required parameter 'userId' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");
            // verify the required parameter 'observationType' is set
            if (observationType == null)
                throw new ApiException(400, "Missing required parameter 'observationType' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");
            // verify the required parameter 'queryType' is set
            if (queryType == null)
                throw new ApiException(400, "Missing required parameter 'queryType' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");
            // verify the required parameter 'pastDays' is set
            if (pastDays == null)
                throw new ApiException(400, "Missing required parameter 'pastDays' when calling ObservationsApi->MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet");

            var localVarPath = "./mynhs/{userId}/observations/summaries/{observationType}/{queryType}/{pastDays}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (userId != null) localVarPathParams.Add("userId", this.Configuration.ApiClient.ParameterToString(userId)); // path parameter
            if (observationType != null) localVarPathParams.Add("observationType", this.Configuration.ApiClient.ParameterToString(observationType)); // path parameter
            if (queryType != null) localVarPathParams.Add("queryType", this.Configuration.ApiClient.ParameterToString(queryType)); // path parameter
            if (pastDays != null) localVarPathParams.Add("pastDays", this.Configuration.ApiClient.ParameterToString(pastDays)); // path parameter
            // authentication (MyNhsOAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsUserIdObservationsSummariesObservationTypeQueryTypePastDaysGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<NhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => string.Join(",", x.Value)),
                (NhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(NhsProfile)));
        }

    }
}
