#!/usr/bin/env bash
#
# Generated by: https://github.com/swagger-api/swagger-codegen.git
#

dotnet restore src/mynhs/ && \
    dotnet build src/mynhs/ && \
    echo "Now, run the following to start the project: dotnet run -p src/mynhs/mynhs.csproj --launch-profile web"
