/*
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace mynhs.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BloodPressureResult : IEquatable<BloodPressureResult>
    { 
        /// <summary>
        /// Gets or Sets BloodPressureCategory
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum BloodPressureCategoryEnum
        {
            /// <summary>
            /// Enum NormalEnum for Normal
            /// </summary>
            [EnumMember(Value = "Normal")]
            NormalEnum = 0,
            /// <summary>
            /// Enum ElevatedEnum for Elevated
            /// </summary>
            [EnumMember(Value = "Elevated")]
            ElevatedEnum = 1,
            /// <summary>
            /// Enum HypertensionStage1Enum for Hypertension Stage 1
            /// </summary>
            [EnumMember(Value = "Hypertension Stage 1")]
            HypertensionStage1Enum = 2,
            /// <summary>
            /// Enum HypertensionStage2Enum for Hypertension Stage 2
            /// </summary>
            [EnumMember(Value = "Hypertension Stage 2")]
            HypertensionStage2Enum = 3,
            /// <summary>
            /// Enum HypertensiveCrisisEnum for Hypertensive Crisis
            /// </summary>
            [EnumMember(Value = "Hypertensive Crisis")]
            HypertensiveCrisisEnum = 4        }

        /// <summary>
        /// Gets or Sets BloodPressureCategory
        /// </summary>

        [DataMember(Name="BloodPressureCategory")]
        public BloodPressureCategoryEnum? BloodPressureCategory { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BloodPressureResult {\n");
            sb.Append("  BloodPressureCategory: ").Append(BloodPressureCategory).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BloodPressureResult)obj);
        }

        /// <summary>
        /// Returns true if BloodPressureResult instances are equal
        /// </summary>
        /// <param name="other">Instance of BloodPressureResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BloodPressureResult other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    BloodPressureCategory == other.BloodPressureCategory ||
                    BloodPressureCategory != null &&
                    BloodPressureCategory.Equals(other.BloodPressureCategory)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (BloodPressureCategory != null)
                    hashCode = hashCode * 59 + BloodPressureCategory.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BloodPressureResult left, BloodPressureResult right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BloodPressureResult left, BloodPressureResult right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
