/*
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace mynhs.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DigitalHealthCheckRequest : IEquatable<DigitalHealthCheckRequest>
    { 
        /// <summary>
        /// Gets or Sets Height
        /// </summary>

        [DataMember(Name="Height")]
        public Height Height { get; set; }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>

        [DataMember(Name="Weight")]
        public Mass Weight { get; set; }

        /// <summary>
        /// Gets or Sets BloodPressure
        /// </summary>

        [DataMember(Name="BloodPressure")]
        public BloodPressure BloodPressure { get; set; }

        /// <summary>
        /// Gets or Sets BloodSugar
        /// </summary>

        [DataMember(Name="BloodSugar")]
        public string BloodSugar { get; set; }

        /// <summary>
        /// Gets or Sets Colesterol
        /// </summary>

        [DataMember(Name="Colesterol")]
        public string Colesterol { get; set; }

        /// <summary>
        /// Gets or Sets Ethnicity
        /// </summary>

        [DataMember(Name="Ethnicity")]
        public string Ethnicity { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DigitalHealthCheckRequest {\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  BloodPressure: ").Append(BloodPressure).Append("\n");
            sb.Append("  BloodSugar: ").Append(BloodSugar).Append("\n");
            sb.Append("  Colesterol: ").Append(Colesterol).Append("\n");
            sb.Append("  Ethnicity: ").Append(Ethnicity).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DigitalHealthCheckRequest)obj);
        }

        /// <summary>
        /// Returns true if DigitalHealthCheckRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of DigitalHealthCheckRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DigitalHealthCheckRequest other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Height == other.Height ||
                    Height != null &&
                    Height.Equals(other.Height)
                ) && 
                (
                    Weight == other.Weight ||
                    Weight != null &&
                    Weight.Equals(other.Weight)
                ) && 
                (
                    BloodPressure == other.BloodPressure ||
                    BloodPressure != null &&
                    BloodPressure.Equals(other.BloodPressure)
                ) && 
                (
                    BloodSugar == other.BloodSugar ||
                    BloodSugar != null &&
                    BloodSugar.Equals(other.BloodSugar)
                ) && 
                (
                    Colesterol == other.Colesterol ||
                    Colesterol != null &&
                    Colesterol.Equals(other.Colesterol)
                ) && 
                (
                    Ethnicity == other.Ethnicity ||
                    Ethnicity != null &&
                    Ethnicity.Equals(other.Ethnicity)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Height != null)
                    hashCode = hashCode * 59 + Height.GetHashCode();
                    if (Weight != null)
                    hashCode = hashCode * 59 + Weight.GetHashCode();
                    if (BloodPressure != null)
                    hashCode = hashCode * 59 + BloodPressure.GetHashCode();
                    if (BloodSugar != null)
                    hashCode = hashCode * 59 + BloodSugar.GetHashCode();
                    if (Colesterol != null)
                    hashCode = hashCode * 59 + Colesterol.GetHashCode();
                    if (Ethnicity != null)
                    hashCode = hashCode * 59 + Ethnicity.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DigitalHealthCheckRequest left, DigitalHealthCheckRequest right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DigitalHealthCheckRequest left, DigitalHealthCheckRequest right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
