/*
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace mynhs.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DigitalHealthCheckRequestAll : IEquatable<DigitalHealthCheckRequestAll>
    { 
        /// <summary>
        /// Gets or Sets Age
        /// </summary>
        [Required]

        [DataMember(Name="Age")]
        public Age Age { get; set; }

        /// <summary>
        /// Gets or Sets Height
        /// </summary>
        [Required]

        [DataMember(Name="Height")]
        public Height Height { get; set; }

        /// <summary>
        /// Gets or Sets Weight
        /// </summary>
        [Required]

        [DataMember(Name="Weight")]
        public Mass Weight { get; set; }

        /// <summary>
        /// Gets or Sets BloodPressure
        /// </summary>
        [Required]

        [DataMember(Name="BloodPressure")]
        public BloodPressure BloodPressure { get; set; }

        /// <summary>
        /// Gets or Sets BloodSugar
        /// </summary>
        [Required]

        [DataMember(Name="BloodSugar")]
        public BloodSugar BloodSugar { get; set; }

        /// <summary>
        /// Gets or Sets Colesterol
        /// </summary>
        [Required]

        [DataMember(Name="Colesterol")]
        public Colesterol Colesterol { get; set; }

        /// <summary>
        /// Gets or Sets Ethnicity
        /// </summary>
        [Required]

        [DataMember(Name="Ethnicity")]
        public string Ethnicity { get; set; }

        /// <summary>
        /// Gets or Sets AlcoholUse
        /// </summary>
        [Required]

        [DataMember(Name="AlcoholUse")]
        public long? AlcoholUse { get; set; }

        /// <summary>
        /// Gets or Sets Smoking
        /// </summary>
        [Required]

        [DataMember(Name="Smoking")]
        public long? Smoking { get; set; }

        /// <summary>
        /// Gets or Sets PhysicalActivity
        /// </summary>
        [Required]

        [DataMember(Name="PhysicalActivity")]
        public long? PhysicalActivity { get; set; }

        /// <summary>
        /// Gets or Sets FamilyHistory
        /// </summary>
        [Required]

        [DataMember(Name="FamilyHistory")]
        public long? FamilyHistory { get; set; }

        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [Required]

        [DataMember(Name="Gender")]
        public string Gender { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DigitalHealthCheckRequestAll {\n");
            sb.Append("  Age: ").Append(Age).Append("\n");
            sb.Append("  Height: ").Append(Height).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("  BloodPressure: ").Append(BloodPressure).Append("\n");
            sb.Append("  BloodSugar: ").Append(BloodSugar).Append("\n");
            sb.Append("  Colesterol: ").Append(Colesterol).Append("\n");
            sb.Append("  Ethnicity: ").Append(Ethnicity).Append("\n");
            sb.Append("  AlcoholUse: ").Append(AlcoholUse).Append("\n");
            sb.Append("  Smoking: ").Append(Smoking).Append("\n");
            sb.Append("  PhysicalActivity: ").Append(PhysicalActivity).Append("\n");
            sb.Append("  FamilyHistory: ").Append(FamilyHistory).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DigitalHealthCheckRequestAll)obj);
        }

        /// <summary>
        /// Returns true if DigitalHealthCheckRequestAll instances are equal
        /// </summary>
        /// <param name="other">Instance of DigitalHealthCheckRequestAll to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DigitalHealthCheckRequestAll other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Age == other.Age ||
                    Age != null &&
                    Age.Equals(other.Age)
                ) && 
                (
                    Height == other.Height ||
                    Height != null &&
                    Height.Equals(other.Height)
                ) && 
                (
                    Weight == other.Weight ||
                    Weight != null &&
                    Weight.Equals(other.Weight)
                ) && 
                (
                    BloodPressure == other.BloodPressure ||
                    BloodPressure != null &&
                    BloodPressure.Equals(other.BloodPressure)
                ) && 
                (
                    BloodSugar == other.BloodSugar ||
                    BloodSugar != null &&
                    BloodSugar.Equals(other.BloodSugar)
                ) && 
                (
                    Colesterol == other.Colesterol ||
                    Colesterol != null &&
                    Colesterol.Equals(other.Colesterol)
                ) && 
                (
                    Ethnicity == other.Ethnicity ||
                    Ethnicity != null &&
                    Ethnicity.Equals(other.Ethnicity)
                ) && 
                (
                    AlcoholUse == other.AlcoholUse ||
                    AlcoholUse != null &&
                    AlcoholUse.Equals(other.AlcoholUse)
                ) && 
                (
                    Smoking == other.Smoking ||
                    Smoking != null &&
                    Smoking.Equals(other.Smoking)
                ) && 
                (
                    PhysicalActivity == other.PhysicalActivity ||
                    PhysicalActivity != null &&
                    PhysicalActivity.Equals(other.PhysicalActivity)
                ) && 
                (
                    FamilyHistory == other.FamilyHistory ||
                    FamilyHistory != null &&
                    FamilyHistory.Equals(other.FamilyHistory)
                ) && 
                (
                    Gender == other.Gender ||
                    Gender != null &&
                    Gender.Equals(other.Gender)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Age != null)
                    hashCode = hashCode * 59 + Age.GetHashCode();
                    if (Height != null)
                    hashCode = hashCode * 59 + Height.GetHashCode();
                    if (Weight != null)
                    hashCode = hashCode * 59 + Weight.GetHashCode();
                    if (BloodPressure != null)
                    hashCode = hashCode * 59 + BloodPressure.GetHashCode();
                    if (BloodSugar != null)
                    hashCode = hashCode * 59 + BloodSugar.GetHashCode();
                    if (Colesterol != null)
                    hashCode = hashCode * 59 + Colesterol.GetHashCode();
                    if (Ethnicity != null)
                    hashCode = hashCode * 59 + Ethnicity.GetHashCode();
                    if (AlcoholUse != null)
                    hashCode = hashCode * 59 + AlcoholUse.GetHashCode();
                    if (Smoking != null)
                    hashCode = hashCode * 59 + Smoking.GetHashCode();
                    if (PhysicalActivity != null)
                    hashCode = hashCode * 59 + PhysicalActivity.GetHashCode();
                    if (FamilyHistory != null)
                    hashCode = hashCode * 59 + FamilyHistory.GetHashCode();
                    if (Gender != null)
                    hashCode = hashCode * 59 + Gender.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DigitalHealthCheckRequestAll left, DigitalHealthCheckRequestAll right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DigitalHealthCheckRequestAll left, DigitalHealthCheckRequestAll right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
