/*
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class DigitalHealthChecksApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/age")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidAgeGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidAgeGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/bloodpressure")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidBloodpressureGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidBloodpressureGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/bloodsugar")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidBloodsugarGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidBloodsugarGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/colesterol")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidColesterolGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidColesterolGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/height")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidHeightGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidHeightGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/weight")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidWeightGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidWeightGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="healthcheckid"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/digitalhealthchecks/{healthcheckid}/wellnessquestions")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyDigitalhealthchecksHealthcheckidWellnessquestionsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyDigitalhealthchecksHealthcheckidWellnessquestionsGet([FromRoute][Required]string healthcheckid)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
