/*
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;
using IO.Swagger.Security;
using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class ObservationsApiController : ControllerBase
    { 
        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/observations/bloodpressures")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyObservationsBloodpressuresGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyObservationsBloodpressuresGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="type"></param>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/observations")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyObservationsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyObservationsGet([FromQuery][Required()]string type)
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/observations/heights")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyObservationsHeightsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyObservationsHeightsGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <response code="200">OK</response>
        [HttpGet]
        [Route("/NHSX/MyNhs/0.1/mynhs/my/observations/weights")]
        [ValidateModelState]
        [SwaggerOperation("MynhsMyObservationsWeightsGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(NhsProfile), description: "OK")]
        public virtual IActionResult MynhsMyObservationsWeightsGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(NhsProfile));
            string exampleJson = null;
            exampleJson = "{\n  \"NhsNumber\" : 0\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<NhsProfile>(exampleJson)
                        : default(NhsProfile);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
