/* 
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IMedicalRecordsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MyNhsProfile</returns>
        MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsPost ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        ApiResponse<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>MyNhsProfile</returns>
        MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGet (string requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        ApiResponse<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetWithHttpInfo (string requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>MyNhsProfile</returns>
        MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPut (string requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        ApiResponse<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutWithHttpInfo (string requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>MyNhsProfile</returns>
        MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGet (string resultId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        ApiResponse<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetWithHttpInfo (string resultId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MyNhsProfile</returns>
        MyNhsProfile MynhsMyMedicalrecordsSummaryNhsGet ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        ApiResponse<MyNhsProfile> MynhsMyMedicalrecordsSummaryNhsGetWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>MyNhsProfile</returns>
        MyNhsProfile MynhsMyMedicalrecordsSummaryNhsTrustIdGet (string trustId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        ApiResponse<MyNhsProfile> MynhsMyMedicalrecordsSummaryNhsTrustIdGetWithHttpInfo (string trustId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of MyNhsProfile</returns>
        System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetAsync (string requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetAsyncWithHttpInfo (string requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutAsync (string requestId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutAsyncWithHttpInfo (string requestId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetAsync (string resultId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetAsyncWithHttpInfo (string resultId);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of MyNhsProfile</returns>
        System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsSummaryNhsGetAsync ();

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsSummaryNhsGetAsyncWithHttpInfo ();
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsSummaryNhsTrustIdGetAsync (string trustId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsSummaryNhsTrustIdGetAsyncWithHttpInfo (string trustId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class MedicalRecordsApi : IMedicalRecordsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MedicalRecordsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MedicalRecordsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MedicalRecordsApi"/> class
        /// </summary>
        /// <returns></returns>
        public MedicalRecordsApi()
        {
            this.Configuration = IO.Swagger.Client.Configuration.Default;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MedicalRecordsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MedicalRecordsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MyNhsProfile</returns>
        public MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsPost ()
        {
             ApiResponse<MyNhsProfile> localVarResponse = MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        public ApiResponse< MyNhsProfile > MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostWithHttpInfo ()
        {

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of MyNhsProfile</returns>
        public async System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostAsync ()
        {
             ApiResponse<MyNhsProfile> localVarResponse = await MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsPostAsyncWithHttpInfo ()
        {

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>MyNhsProfile</returns>
        public MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGet (string requestId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetWithHttpInfo(requestId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        public ApiResponse< MyNhsProfile > MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetWithHttpInfo (string requestId)
        {
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGet");

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        public async System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetAsync (string requestId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = await MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetAsyncWithHttpInfo(requestId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGetAsyncWithHttpInfo (string requestId)
        {
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGet");

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords/{requestId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>MyNhsProfile</returns>
        public MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPut (string requestId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutWithHttpInfo(requestId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        public ApiResponse< MyNhsProfile > MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutWithHttpInfo (string requestId)
        {
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPut");

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords/{requestId}/submit";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        public async System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutAsync (string requestId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = await MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutAsyncWithHttpInfo(requestId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="requestId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPutAsyncWithHttpInfo (string requestId)
        {
            // verify the required parameter 'requestId' is set
            if (requestId == null)
                throw new ApiException(400, "Missing required parameter 'requestId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPut");

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords/{requestId}/submit";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (requestId != null) localVarPathParams.Add("requestId", this.Configuration.ApiClient.ParameterToString(requestId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsRequestIdSubmitPut", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>MyNhsProfile</returns>
        public MyNhsProfile MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGet (string resultId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetWithHttpInfo(resultId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        public ApiResponse< MyNhsProfile > MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetWithHttpInfo (string resultId)
        {
            // verify the required parameter 'resultId' is set
            if (resultId == null)
                throw new ApiException(400, "Missing required parameter 'resultId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGet");

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords/results/{resultId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (resultId != null) localVarPathParams.Add("resultId", this.Configuration.ApiClient.ParameterToString(resultId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        public async System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetAsync (string resultId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = await MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetAsyncWithHttpInfo(resultId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="resultId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGetAsyncWithHttpInfo (string resultId)
        {
            // verify the required parameter 'resultId' is set
            if (resultId == null)
                throw new ApiException(400, "Missing required parameter 'resultId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGet");

            var localVarPath = "/mynhs/my/medicalrecords/detailed/nhs/requestRecords/results/{resultId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (resultId != null) localVarPathParams.Add("resultId", this.Configuration.ApiClient.ParameterToString(resultId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsDetailedNhsRequestRecordsResultsResultIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MyNhsProfile</returns>
        public MyNhsProfile MynhsMyMedicalrecordsSummaryNhsGet ()
        {
             ApiResponse<MyNhsProfile> localVarResponse = MynhsMyMedicalrecordsSummaryNhsGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        public ApiResponse< MyNhsProfile > MynhsMyMedicalrecordsSummaryNhsGetWithHttpInfo ()
        {

            var localVarPath = "/mynhs/my/medicalrecords/summary/nhs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsSummaryNhsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of MyNhsProfile</returns>
        public async System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsSummaryNhsGetAsync ()
        {
             ApiResponse<MyNhsProfile> localVarResponse = await MynhsMyMedicalrecordsSummaryNhsGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsSummaryNhsGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/mynhs/my/medicalrecords/summary/nhs";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsSummaryNhsGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>MyNhsProfile</returns>
        public MyNhsProfile MynhsMyMedicalrecordsSummaryNhsTrustIdGet (string trustId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = MynhsMyMedicalrecordsSummaryNhsTrustIdGetWithHttpInfo(trustId);
             return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>ApiResponse of MyNhsProfile</returns>
        public ApiResponse< MyNhsProfile > MynhsMyMedicalrecordsSummaryNhsTrustIdGetWithHttpInfo (string trustId)
        {
            // verify the required parameter 'trustId' is set
            if (trustId == null)
                throw new ApiException(400, "Missing required parameter 'trustId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsSummaryNhsTrustIdGet");

            var localVarPath = "/mynhs/my/medicalrecords/summary/nhs/{trustId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (trustId != null) localVarPathParams.Add("trustId", this.Configuration.ApiClient.ParameterToString(trustId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsSummaryNhsTrustIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>Task of MyNhsProfile</returns>
        public async System.Threading.Tasks.Task<MyNhsProfile> MynhsMyMedicalrecordsSummaryNhsTrustIdGetAsync (string trustId)
        {
             ApiResponse<MyNhsProfile> localVarResponse = await MynhsMyMedicalrecordsSummaryNhsTrustIdGetAsyncWithHttpInfo(trustId);
             return localVarResponse.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="trustId"></param>
        /// <returns>Task of ApiResponse (MyNhsProfile)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MyNhsProfile>> MynhsMyMedicalrecordsSummaryNhsTrustIdGetAsyncWithHttpInfo (string trustId)
        {
            // verify the required parameter 'trustId' is set
            if (trustId == null)
                throw new ApiException(400, "Missing required parameter 'trustId' when calling MedicalRecordsApi->MynhsMyMedicalrecordsSummaryNhsTrustIdGet");

            var localVarPath = "/mynhs/my/medicalrecords/summary/nhs/{trustId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (trustId != null) localVarPathParams.Add("trustId", this.Configuration.ApiClient.ParameterToString(trustId)); // path parameter
            // authentication (OAuth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MynhsMyMedicalrecordsSummaryNhsTrustIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MyNhsProfile>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
                (MyNhsProfile) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(MyNhsProfile)));
        }

    }
}
