/* 
 * My NHS Graph
 *
 * WIP Strawman API ideas for a Unified API myNHS API Graph endpoint, bringing together both new \"User Generated Data\" and existing sources into one endpoint and one Authorisation model, supporting delegated user access and proxy access. Modeling that the records belong to the \"tennant\" with owners having proxy access (ie full) and users being shared specifics records. Oauth scopes, with modifiers of .shared and .all. Look at Microsoft Graph for where that comes from. To support idempotency, all POST apis are just requests to start something, the put starts this. Alows for evential consistency. Long running GETs are removed, by POSTing requests for data, with a GET endpoint returned.
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// GpProfile
    /// </summary>
    [DataContract]
        public partial class GpProfile :  IEquatable<GpProfile>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GpProfile" /> class.
        /// </summary>
        /// <param name="gpIdCode">gpIdCode.</param>
        public GpProfile(long? gpIdCode = default(long?))
        {
            this.GpIdCode = gpIdCode;
        }
        
        /// <summary>
        /// Gets or Sets GpIdCode
        /// </summary>
        [DataMember(Name="GpIdCode", EmitDefaultValue=false)]
        public long? GpIdCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GpProfile {\n");
            sb.Append("  GpIdCode: ").Append(GpIdCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GpProfile);
        }

        /// <summary>
        /// Returns true if GpProfile instances are equal
        /// </summary>
        /// <param name="input">Instance of GpProfile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GpProfile input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GpIdCode == input.GpIdCode ||
                    (this.GpIdCode != null &&
                    this.GpIdCode.Equals(input.GpIdCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GpIdCode != null)
                    hashCode = hashCode * 59 + this.GpIdCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
